services:
  web:
    build: .
    container_name: flobrain_backend_django
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db

  db:
    image: postgres:15
    container_name: flobrain_backend_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flo_user -d flobrain_db -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: