// File: src/features/ai-pipeline/ai.mock.processor.ts

import {
  SummaryResponse,
  TagsResponse,
  TranscriptionResponse,
} from './ai.types';

const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

class MockAiProcessor {
  //Simule une transcription.

  async transcription(body: { media_url: string }): Promise<TranscriptionResponse> {
    await wait(1500); 
    return {
      text: 'This is a sample transcript generated by the mock AI service. It is not a real transcription but serves as a placeholder for development.',
      model_name: 'mock-whisper-v1',
      model_version: '1.0.0',
      latency_ms: 1500,
    };
  }
  // Simulate a summary.
 
  async summary(body: { text: string }): Promise<SummaryResponse> {
    await wait(500); // Simulate 0.5 seconds of processing
    
    return {
      summary: 'This is a mock summary. The service successfully processed the input text and generated this placeholder summary.',
      model_name: 'mock-summarizer-v1',
      model_version: '1.0.0',
      latency_ms: 500,
    };
  }
  // Simulate tag generation.
  
  async tags(body: { text: string }): Promise<TagsResponse> {
    await wait(300); // Simulate 0.3 seconds of processing
    
    return {
      tags: ['mock', 'sample-data', 'placeholder', 'development', 'ai-service'],
      model_name: 'mock-tagger-v1',
      model_version: '1.0.0',
      latency_ms: 300,
    };
  }
}
// We export a single instance of our processor
export const mockAiProcessor = new MockAiProcessor();