# Generated by Django 5.2 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("provider_name", models.CharField(max_length=200)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("open-source", "Open source"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("supported_input_types", models.JSONField(default=list)),
                ("capabilities", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_model_registry",
                "ordering": ["provider_name", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_name", "name"),
                        name="unique_ai_model_per_provider",
                    )
                ],
            },
        ),
    ]
