# Generated by Django 5.2.16 on 2026-07-21 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryNode',
            fields=[
                ('id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, default='system', max_length=64)),
                ('name', models.TextField(default='untitled')),
                ('binary_index', models.IntegerField(db_index=True, default=1)),
                ('tier_level', models.IntegerField(choices=[(1, 'Tier 1: Active Buffer'), (2, 'Tier 2: Associative Layer'), (3, 'Tier 3: Cold Vault')], default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('memory_type', models.CharField(choices=[('chunk', 'Chunk'), ('summary', 'Summary'), ('interaction', 'Interaction'), ('workflow', 'Workflow')], db_index=True, default='chunk', max_length=32)),
                ('relevance', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('size_bytes', models.PositiveIntegerField(default=0, help_text='Size of raw or compressed payload')),
                ('is_locked', models.BooleanField(default=False, help_text='Prevents GC from touching this node')),
            ],
            options={
                'db_table': 'memory_nodes',
                'indexes': [models.Index(fields=['tier_level', 'created_at'], name='memory_node_tier_le_1946e1_idx'), models.Index(fields=['owner_id', 'tier_level'], name='memory_node_owner_i_663931_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ref_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_accessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('frequency_score', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'token_dictionary',
                'indexes': [models.Index(fields=['frequency_score', 'last_accessed_at'], name='token_dicti_frequen_17bc5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(default='associated', max_length=64)),
                ('weight', models.FloatField(default=0.5)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='memory.memorynode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='memory.memorynode')),
            ],
            options={
                'db_table': 'memory_links',
                'indexes': [models.Index(fields=['source', 'target', 'weight'], name='memory_link_source__fca533_idx')],
            },
        ),
    ]
