site_name: CAIPO Docs
repo_url: https://github.com/FlomadLabsRD/Caipo-flomad-labs-updated
theme:
  name: material
  features: [navigation.instant, content.code.copy]
nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Server (API): server.md
  - Firmware (TBD): firmware.md
  - Simulation (TBD): simulation.md
  - Hardware (TBD): hardware.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
