[env:esp32dev]
platform = espressif32
framework = arduino
board = seeed_xiao_esp32s3     ; or your board
lib_deps =
  bblanchon/ArduinoJson @ ^6.20.0
  SPIFFS
build_flags =
  -DCONFIG_CAMERA_TASK_STACK_SIZE=4096
  -DFAISS_EMBEDDED
board_build.partitions = custom.csv
